# Generated by Django 3.2.4 on 2021-06-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Add description of the function'),
        ),
        migrations.AlterField(
            model_name='math',
            name='func',
            field=models.TextField(max_length=50, verbose_name='Pass the python function with proper indentation, make sure function name is same as operation name'),
        ),
    ]
